### PR TITLE
Update to 0.2.7

### PR DESCRIPTION
**Pull request by ocefpaf**

### CODE REVIEW

**Comment by jakirkham** [comment]
Hmm...at the same time this was merged an empty repository named `dataspyre` showed up. Interestingly this recipe also names itself `dataspyre`. Maybe some service created the repository by accident? Any ideas @isuruf?

**Comment by isuruf** [comment]
Who created the empty repo? @conda-forge-admin or @conda-forge-linter ?

**Comment by jakirkham** [comment]
@conda-forge-linter, it appears. Snippet from the Audit Log below. Last entry is first chronologically and vice versa.

<details>
<summary>Log:</summary>

```
@conda-forge-linter @ocefpaf
conda-forge-linter – team.add_member
Added ocefpaf to the conda-forge/dataspyre team
Unknown location 11 hours ago

@conda-forge-linter
conda-forge-linter – team.add_repository
Gave conda-forge/dataspyre access to conda-forge/dataspyre-feedstock
Unknown location 11 hours ago

@conda-forge-linter
conda-forge-linter – team.create
Created the team conda-forge/dataspyre
Unknown location 11 hours ago

@conda-forge-linter
conda-forge-linter – repo.create
Created the repository conda-forge/dataspyre-feedstock
Unknown location 11 hours ago
```

</details>

**Comment by jakirkham** [comment]
Think this is caused by team update services, but the real cause is `conda-smithy`. Basically we are calling `register-github` with `conda-smithy`, which creates the repo and then adds the team. In this case, neither existed; so, it added both. Maybe we can do a bit of refactoring in `conda-smithy` to get a command for just updating a team. Though this is only one problem.

The other problem is that renaming a package to differ from the feedstock effectively breaks the team update service currently. Not entirely sure of a good way to fix that ATM.

**Comment by jakirkham** [comment]
Raised as issue ( https://github.com/conda-forge/conda-smithy/issues/624 ) for now. Feel free to add more details.

**Pull request merged**
